services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn crm.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        value: 'postgres://postgres:Salmaan%231997@database-2.cfmeogaiioso.ap-south-1.rds.amazonaws.com:5432/demo_1'
      - key: EMAIL_HOST_USER
        value: 'djangotestmail1997@gmail.com'
      - key: EMAIL_HOST_PASSWORD
        value: 'unry auzn rrku jlbw'
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
